backend:
  name: github
  repo: shoushou-design/shoushou-design  # your repo name
  branch: main
  auth_type: token
  token: ghp_your_token_here

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Product Name", widget: "string" }
      - { name: "price", label: "Price (DZD)", widget: "number" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "image", label: "Product Image", widget: "image" }
      - { name: "featured", label: "Featured Product", widget: "boolean", default: false }
